// Embeds the MS YaHei font files as base64 into a generated TS module so the
// PDF exporter never depends on a runtime `fetch` (which in a Tauri production
// build can resolve to a stale/wrong asset and produce garbled output).
// Run automatically before `vite build` and `vite dev` via package.json scripts.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

function enc(rel) {
  const p = join(root, rel);
  if (!existsSync(p)) {
    throw new Error("Missing font file required for PDF export: " + p);
  }
  return readFileSync(p).toString("base64");
}

const msyh = enc("public/fonts/msyh.ttf");
const msyhbd = enc("public/fonts/msyhbd.ttf");

const out =
  "// AUTO-GENERATED by scripts/embed-fonts.mjs — do not edit by hand.\n" +
  "// Base64-encoded MS YaHei (Regular + Bold). Lets the PDF exporter embed the\n" +
  "// exact, verified font bytes with no runtime fetch (avoids Tauri prod-asset\n" +
  "// path issues that produced garbled/huge-spacing PDFs).\n" +
  "export const MSYH_TTF_B64: string = " + JSON.stringify(msyh) + ";\n" +
  "export const MSYHBD_TTF_B64: string = " + JSON.stringify(msyhbd) + ";\n";

const libDir = join(root, "src", "lib");
mkdirSync(libDir, { recursive: true });
writeFileSync(join(libDir, "_fontBytes.generated.ts"), out);
console.log(
  "generated src/lib/_fontBytes.generated.ts (" +
    (out.length / 1024 / 1024).toFixed(1) +
    " MB)"
);
